- name: build
  tasks:
    - webpack
    - - prepend bin/index.js '#!/usr/bin/env node\n\n'

- name: test
  tasks:
    - taskfile lint
    - taskfile spec

- name: lint
  task: xo src/*.js

- name: spec
  task: NODE_ENV= nyc ava
